name: Java 17 Maven Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    
    # 设置 Java 17 环境
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}
        cache: 'maven'  # 新增 Maven 依赖缓存

    # 验证 Java 版本
    - name: Verify Java version
      run: java -version

    # 带智能缓存的构建
    - name: Build with Maven
      run: |
        mvn -B verify -DskipTests
        # 列出生成的 artifact 用于调试
        ls -lh target/*.jar

    # 发布到 GitHub Packages
    - name: Publish to GitHub Packages
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MAVEN_USERNAME: ${{ github.actor }}
        MAVEN_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

    # 可选：上传到 Releases
    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: target/*.jar
        asset_name: ${{ github.event.repository.name }}-${{ github.event.release.tag_name }}.jar
        asset_content_type: application/java-archive
      if: success() && github.event_name == 'release'
