name: Java 17 Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    # 设置 Java 17
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'

    # 构建并生成带依赖的fat jar是的
    - name: Build with Maven
      run: |
        mvn clean package
        jar --list --file target/*.jar | grep org/spigotmc  # 验证spigot依赖

    # 创建版本发布
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        files: |
          target/*.jar
          LICENSE
        draft: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # 可选：上传到Maven仓库
    - name: Publish to Maven Central
      if: success()
      run: mvn deploy -DskipTests
      env:
        MAVEN_USERNAME: ${{ secrets.OSS_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.OSS_PASSWORD }}
